
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : tp2
//  @ File Name : Machine.java
//  @ Date : 2014-06-06
//  @ Author : Guehel Bouanga
//
//

package tp2.reseau.model;



import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;



/** 
 * Thread heritant de service abstrait specialise dans  la decouverte du reseau 
 * */
public class DecouverteReseau extends ServiceAbstrait {
	private static final int NOMBRE_DE_POSTES = 254;
	private  byte[] ipLocale ; 
	
	/**Contructeur
	 * @param observateur machine locale qui va etre notifie des resultats
	 * @param ipLocale adresse Ip de la machine ip sous forme de tableau de 4 bytes
	 */
	public DecouverteReseau(Observateur observateur , byte[] ipLocale) {
		super(observateur);
		this.ipLocale = ipLocale;
	}
	/**
	 * Contenu de la methode Run
	 * creer un flux entrant du fichier 
	 * creer un flux sortant vers le client  */
	public void demarrer() {
	ScheduledExecutorService executor = Executors.newScheduledThreadPool(500);
		
		for(int i = 0; i < NOMBRE_DE_POSTES; i++){
			ipLocale[3] = (byte)i;
			TacheAdresse tacheAdresse;
			try {
				InetAddress inetAdresse = InetAddress.getByAddress(ipLocale);
				tacheAdresse = new TacheAdresse(inetAdresse, this.observateur);
				executor.scheduleAtFixedRate(tacheAdresse, 0, 1, TimeUnit.MINUTES);
			} catch (UnknownHostException e) {
				e.printStackTrace();
				System.out.println("erreur Machine factory");
			}
		}
	
	}
	
	/** */
	public boolean reussie() {
		return false;
	}

	
	
}
