

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : tp2
//  @ File Name : Machine.java
//  @ Date : 2014-06-06
//  @ Author : Guehel Bouanga
//
//
package tp2.reseau.model;

import java.net.InetAddress;





/**
 * Object representant un ordinateur actif sur le reseau
 *  */
public class Machine {
	private String nom;
	private String nomComplet;
	private String adresseIp;
	private boolean active;
	public Machine(String adresse) {
		adresseIp = adresse;// TODO Auto-generated constructor stub
	}
	
	public Machine(){}
	public Machine(InetAddress localHost) {
		super();
		this.nom = localHost.getHostName();
		this.nomComplet = localHost.getCanonicalHostName();
		this.adresseIp = localHost.getHostAddress();
		this.active = true;
	}
	public String getNom() {
		return nom;
	}
	public String getNomComplet() {
		return nomComplet;
	}
	public String getAdresseIP() {
		return adresseIp;
	}
	public boolean estActive() {
		return active;
	}
	public String getAdresseIp() {
		return adresseIp;
	}
	public void setAdresseIp(String adresseIp) {
		this.adresseIp = adresseIp;
	}
	public boolean isActive() {
		return active;
	}
	
	public void setNom(String nom) {
		this.nom = nom;
	}
	public void setNomComplet(String nomComplet) {
		this.nomComplet = nomComplet;
		
	}

	public void setActive(boolean reachable) {
		active = reachable;
		
	}
	
}
