package tp2.reseau.model;

import java.util.Map;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Observateur.java
//  @ Date : 2014-06-06
//  @ Author : 
//
//




/** */
/**Interface qui defini les methode que doivent implementer tous les observateurs
 * @author boug18087415
 *
 */
public interface Observateur {
	/** Utilisee lors que l'observaeur attend une machine comme parametre
	 * Exemple l'ajout de machine
	 * */
	public void update(Machine machine);
	
	/** 
	 * Utilisee lorsque l'observateur attend une liste de machines */
	public void update(Map<String, Machine> voisins);
	/** */
	
	public void update(String nomMachine);
	
	/** */
	public void update(boolean reussiteService);
}
