package tp2.reseau.model;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Map;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TacheAdresse.java
//  @ Date : 2014-06-04
//  @ Author : Guehel Bouanga
//
//




/**Runnable qui se charde la creation de l'objet machine 
 * @author guehel
 *
 */
public class TacheAdresse extends ServiceAbstrait {

	private InetAddress inetAdresse;
	public TacheAdresse(InetAddress adresse, Observateur machineLocale) throws UnknownHostException{
		super(machineLocale);
		this.inetAdresse = adresse;

	}


	/**
	 * Contenu de la methode Run
	 * creer un flux entrant du fichier 
	 * creer un flux sortant vers le client  */
	@Override
	public void demarrer() {

		try {

			boolean reachable = inetAdresse.isReachable(3000);
			Machine machine=null;
			if(reachable){
				machine = new Machine(inetAdresse);
				notify(machine);
			}


		} catch (IOException e) {

		}
	}
	/**
	 * Methode de la classe abstrainte non utilisee*/

	@Override
	public boolean reussie() {
		// TODO Auto-generated method stub
		return false;
	}








}
