package Modele.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the t_contact table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="t_contact"
 */
public abstract class BaseTContact  implements Serializable {

	public static String PROP_NOM = "Nom";
	public static String PROP_AGE = "Age";
	public static String PROP_PRENOM = "Prenom";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _prenom;
	private java.lang.Integer _age;
	private java.lang.String _nom;


	// constructors
	public BaseTContact () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTContact (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTContact (
		java.lang.Integer _id,
		java.lang.String _prenom,
		java.lang.Integer _age,
		java.lang.String _nom) {

		this.setId(_id);
		this.setPrenom(_prenom);
		this.setAge(_age);
		this.setNom(_nom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: prenom
	 */
	public java.lang.String getPrenom () {
		return _prenom;
	}

	/**
	 * Set the value related to the column: prenom
	 * @param _prenom the prenom value
	 */
	public void setPrenom (java.lang.String _prenom) {
		this._prenom = _prenom;
	}


	/**
	 * Return the value associated with the column: age
	 */
	public java.lang.Integer getAge () {
		return _age;
	}

	/**
	 * Set the value related to the column: age
	 * @param _age the age value
	 */
	public void setAge (java.lang.Integer _age) {
		this._age = _age;
	}


	/**
	 * Return the value associated with the column: nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof Modele.base.BaseTContact)) return false;
		else {
			Modele.base.BaseTContact mObj = (Modele.base.BaseTContact) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}