/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tp2.reseau.vue;

import javax.swing.JButton;
import javax.swing.JTextField;

/**Panneau pour afficher une machine
 *
 * @author boug18087415
 */
public class PnlMachine extends javax.swing.JPanel {

    /**
     * Creates new form PnlMachine
     */
    public PnlMachine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNomLocal = new javax.swing.JLabel();
        lblNomCLocal = new javax.swing.JLabel();
        lblIPLocalm = new javax.swing.JLabel();
        lblIPLoop = new javax.swing.JLabel();
        lblTitre = new javax.swing.JLabel();
        btnDemarrer = new javax.swing.JButton();
        txtFichier = new javax.swing.JTextField();

        jLabel2.setText("Nom :");

        jLabel3.setText("Adresse IP :");

        jLabel4.setText("IP boocle locale:");

        jLabel5.setText("Nom complet:");

        lblNomLocal.setText("");

        lblNomCLocal.setText("");

        lblIPLocalm.setText("");

        lblIPLoop.setText("");

        lblTitre.setText("MACHINE LOCALE");	

        btnDemarrer.setText("Envoyer fichier");
//        btnDemarrer.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnDemarrerActionPerformed(evt);
//            }
//        });

        txtFichier.setEditable(false);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNomLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNomCLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(lblIPLocalm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIPLoop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnDemarrer)
                            .addComponent(txtFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addContainerGap(21, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblTitre)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitre)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNomLocal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNomCLocal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIPLocalm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblIPLoop))
                .addGap(33, 33, 33)
                .addComponent(btnDemarrer)
                .addGap(29, 29, 29)
                .addComponent(txtFichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDemarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemarrerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDemarrerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnDemarrer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTitre;
    protected javax.swing.JLabel lblIPLocalm;
    protected javax.swing.JLabel lblIPLoop;
    protected javax.swing.JLabel lblNomCLocal;
    protected javax.swing.JLabel lblNomLocal;
    protected javax.swing.JTextField txtFichier;
    // End of variables declaration//GEN-END:variables
	public JButton getBtn() {
		// TODO Auto-generated method stub
		return btnDemarrer;
	}

	

	public javax.swing.JLabel getLblNomLocal() {
		return lblNomLocal;
	}

	public javax.swing.JLabel getLblIPLocalm() {
		return lblIPLocalm;
	}

	public javax.swing.JLabel getLblIPLoop() {
		return lblIPLoop;
	}

	public javax.swing.JLabel getLblNomCLocal() {
		return lblNomCLocal;
	}

	public JTextField getTextField() {
	
		return txtFichier;
	}

	public void setTitre(String string) {
		lblTitre.setText(string);
		
	}
}
