package Modele.dao;

import Modele.base.BaseTContactDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the t_contact table.
 * Any customizations belong here.
 */
public class TContactDAO extends BaseTContactDAO {
}