package vente.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the commentaire table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="commentaire"
 */
public abstract class BaseCommentaire  implements Serializable {

	public static String PROP_CONTENU_COM = "ContenuCom";
	public static String PROP_DATE_COM = "DateCom";
	public static String PROP_ID = "Id";
	public static String PROP_AUTEUR_COM = "AuteurCom";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private vente.CommentairePK _id;

	// fields
	private java.lang.String _auteurCom;
	private java.lang.String _contenuCom;
	private java.util.Date _dateCom;


	// constructors
	public BaseCommentaire () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCommentaire (vente.CommentairePK _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCommentaire (
		vente.CommentairePK _id,
		java.lang.String _auteurCom,
		java.lang.String _contenuCom,
		java.util.Date _dateCom) {

		this.setId(_id);
		this.setAuteurCom(_auteurCom);
		this.setContenuCom(_contenuCom);
		this.setDateCom(_dateCom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     */
	public vente.CommentairePK getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (vente.CommentairePK _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: auteurCom
	 */
	public java.lang.String getAuteurCom () {
		return _auteurCom;
	}

	/**
	 * Set the value related to the column: auteurCom
	 * @param _auteurCom the auteurCom value
	 */
	public void setAuteurCom (java.lang.String _auteurCom) {
		this._auteurCom = _auteurCom;
	}


	/**
	 * Return the value associated with the column: contenuCom
	 */
	public java.lang.String getContenuCom () {
		return _contenuCom;
	}

	/**
	 * Set the value related to the column: contenuCom
	 * @param _contenuCom the contenuCom value
	 */
	public void setContenuCom (java.lang.String _contenuCom) {
		this._contenuCom = _contenuCom;
	}


	/**
	 * Return the value associated with the column: dateCom
	 */
	public java.util.Date getDateCom () {
		return _dateCom;
	}

	/**
	 * Set the value related to the column: dateCom
	 * @param _dateCom the dateCom value
	 */
	public void setDateCom (java.util.Date _dateCom) {
		this._dateCom = _dateCom;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof vente.base.BaseCommentaire)) return false;
		else {
			vente.base.BaseCommentaire mObj = (vente.base.BaseCommentaire) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}